Repository BaguaSys/bagua-core, pull requests merged in 2021-07, with the labels that each got.

#27 fix: fix alltoall_v parameter types
  bagua-core-internal/src/communicators/mod.rs
  bagua-core-py/src/lib.rs
Labels: PR: unreviewed

#26 feat: add native low precision decentralized operator
  bagua-core-internal/kernels/bagua_kernels.cu
  bagua-core-internal/src/comm_ops/decentralized_full_precision_synchronous.rs
  bagua-core-internal/src/comm_ops/decentralized_low_precision_synchronous.rs
  bagua-core-internal/src/comm_ops/mod.rs
  bagua-core-internal/src/datatypes/mod.rs
  bagua-core-internal/src/kernels/mod.rs
  bagua-core-internal/src/lib.rs
  bagua-core-py/src/lib.rs
Labels: PR: unreviewed

#33 fix: make compress/decompress of BaguaTensor `method` string consistent
  bagua-core-internal/src/datatypes/mod.rs
Labels: PR: unreviewed

#37 feat: add (scatter, gather, scatter_reduce) and all inplace version communication primitives
  bagua-core-internal/src/comm_ops/centralized_full_precision_synchronous.rs
  bagua-core-internal/src/comm_ops/centralized_low_precision_synchronous.rs
  bagua-core-internal/src/comm_ops/decentralized_full_precision_synchronous.rs
  bagua-core-internal/src/communicators/mod.rs
  bagua-core-py/src/lib.rs
Labels: PR: reviewed-approved

#40 fix: fix scatter and reduce_scatter implementation
  bagua-core-internal/src/communicators/mod.rs
Labels: PR: reviewed-changes-requested

#39 fix: substract overflow error for decentralized op
  bagua-core-internal/src/comm_ops/decentralized_full_precision_synchronous.rs
Labels: PR: unreviewed

#36 feat: make full precision decentralized op stateless
  bagua-core-internal/src/comm_ops/decentralized_full_precision_synchronous.rs
  bagua-core-internal/src/comm_ops/decentralized_low_precision_synchronous.rs
  bagua-core-internal/src/datatypes/mod.rs
  bagua-core-internal/src/lib.rs
  bagua-core-py/src/lib.rs
Labels: PR: unreviewed

#46 feat: use nccl 2.10 avg op for all algorithms using averaging
  bagua-core-internal/src/comm_ops/centralized_full_precision_synchronous.rs
  bagua-core-internal/src/comm_ops/decentralized_full_precision_synchronous.rs
  bagua-core-internal/src/communicators/mod.rs
Labels: PR: unreviewed
